# Generated by Django 3.0.5 on 2020-10-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicios', '0002_auto_20200825_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
    ]
